kotlin.code.style=official
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx4096M"
org.gradle.parallel=true
org.gradle.daemon=true

# Published version of this repository artifacts (if any are added later).
playgroundVersion=0.1.0-SNAPSHOT

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
