name: Compile
on:
  workflow_call:
    inputs:
      source-sha:
        required: true
        type: string

permissions:
  contents: read

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{ inputs.source-sha }}
          fetch-depth: 0
      - name: Checkout charts
        uses: actions/checkout@v7
        with:
          repository: HDCharts/charts
          path: charts
          fetch-depth: 1
      - uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: 'zulu'
          cache: gradle
      - name: Compile
        run: ./gradlew -DchartsLocalPath=charts ciCompile
