name: Test
on:
  workflow_call:
    inputs:
      should-run:
        required: true
        type: boolean
      source-sha:
        required: true
        type: string

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{ inputs.source-sha }}
          fetch-depth: 0
      - name: Checkout charts
        if: inputs.should-run
        uses: actions/checkout@v7
        with:
          repository: HDCharts/charts
          path: charts
          fetch-depth: 1
      - name: Set up JDK 17
        if: inputs.should-run
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: 'zulu'
          cache: gradle
      - name: Test
        if: inputs.should-run
        run: ./gradlew -DchartsLocalPath=charts playgroundTest
      - name: Skip tests for docs-only changes
        if: ${{ !inputs.should-run }}
        run: echo "No code/build changes detected. Skipping tests."
